# frozen_string_literal: true
source "https://rubygems.org"

# gem "rails"
gem "chef", '12.4.1'
gem "knife-zero", '1.8.0'
gem "berkshelf", '3.3.0'

gem 'rspec'
gem 'capybara'
gem 'selenium-webdriver'
